/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.Conector;
import Entidades.Dcatalogo;
import Entidades.Render;
import static Formularios.Dashboard.content;
import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import static com.sun.jmx.remote.internal.IIOPHelper.connect;
import java.awt.BorderLayout;
import java.awt.Point;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.management.remote.JMXConnectorFactory.connect;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Eterna
 */
public class asientoContable extends javax.swing.JPanel {
      DefaultTableModel jtModelo;
      DefaultTableModel jtModelo1;
      Dcatalogo archivo = new Dcatalogo();
      ArrayList<String> datos;
      TableRowSorter trs ;
      String vcodigo,vnombre,vdebe,vhaber,vfecha,vnumeroAsiento;
      String qry="";
      


    /**
     * Creates new form asientoContable
     */
    public asientoContable() {
        initComponents();
        jtModelo = (DefaultTableModel) this.tcodigos.getModel();   
        jtModelo1 = (DefaultTableModel) this.tasiento.getModel();   
        this.cargarParametros();
        this.cargarT2();

    }
    //cargar tabla de catalogo de cuenta
    public void cargarT2(){

        String[] datosN = new String[2]; 
        datos = archivo.leerDato();
        for (int i = 0; i < datos.size()-1; i++) {
            datosN = datos.get(i).split(",");
            jtModelo.addRow(datosN);

        }  
    } 
    //pasar valores de catalogo de cuenta a jtext para el insert
    public void cargarParametros(){
        tcodigos.addMouseListener(new MouseAdapter (){
            public void mousePressed (MouseEvent Mouse_evt){
                JTable table = (JTable) Mouse_evt.getSource();
                Point point = Mouse_evt.getPoint ();
                int row = table.rowAtPoint(point);
                 if(Mouse_evt.getClickCount()==1){
                     pcodigo.setText (tcodigos.getValueAt(tcodigos.getSelectedRow(),0).toString());
                     pnombre.setText (tcodigos.getValueAt(tcodigos.getSelectedRow(),1).toString());
                 
                 
                 }
            }
        });
     };
    //metodo limpar jtext()
    public void limpiarjtex(){
        this.pcodigo.setText("");
        this.pnombre.setText("");
        this.jtdebe.setText("");
        this.jthaber.setText("");
        fechaA.setCalendar(null);
    }
    //vaciar tabla
    public void eliminar(){
        DefaultTableModel tb = (DefaultTableModel) tasiento.getModel();
        int a = tasiento.getRowCount()-1;
        for (int i = a; i >= 0; i--) {
         tb.removeRow(tb.getRowCount()-1);
        }
        //cargaTicket();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tasiento = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tcodigos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        pcodigo = new javax.swing.JTextField();
        pnombre = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombreE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtcodigoC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaA = new com.toedter.calendar.JDateChooser();
        jtdebe = new javax.swing.JTextField();
        jthaber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(900, 564));

        tasiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tasiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Cuenta", "nombre", "Debe", "Heber", "fecha", "eliminar"
            }
        ));
        tasiento.setCellSelectionEnabled(true);
        tasiento.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tasiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tasientoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tasiento);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jToggleButton1.setText("Terminar Asiento contable");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        tcodigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "nombre"
            }
        ));
        tcodigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tcodigosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tcodigos);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pcodigo.setEditable(false);

        pnombre.setEditable(false);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Ver Asiento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Datos"));

        jLabel1.setText("Empresa:");

        jLabel2.setText("Buscar:");

        jtcodigoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcodigoCActionPerformed(evt);
            }
        });
        jtcodigoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtcodigoCKeyTyped(evt);
            }
        });

        jLabel4.setText("Haber:");

        jLabel5.setText("Fecha:");

        jthaber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jthaberActionPerformed(evt);
            }
        });

        jLabel3.setText("Debe:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jthaber, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fechaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 13, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtcodigoC)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtcodigoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechaA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jtdebe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jthaber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(pcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtcodigoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcodigoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtcodigoCActionPerformed

    private void jtcodigoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtcodigoCKeyTyped
        // TODO add your handling code here:
         jtcodigoC.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke) {
                trs.setRowFilter(RowFilter.regexFilter(jtcodigoC.getText(),1));//To change body of generated methods, choose Tools | Templates.
            }

        });
        
        trs = new TableRowSorter(jtModelo =  (DefaultTableModel) tcodigos.getModel());
        tcodigos.setRowSorter(trs);
    }//GEN-LAST:event_jtcodigoCKeyTyped

    private void tasientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tasientoMouseClicked
        // TODO add your handling code here:
       
        int column = tasiento.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY()/tasiento.getRowHeight();
        
        if(row < tasiento.getRowCount() && row >= 0 && column < tasiento.getColumnCount() && column >= 0){
            Object value = tasiento.getValueAt(row, column);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton boton = (JButton) value;

                if(boton.getName().equals("m")){
                    int a= JOptionPane.showConfirmDialog(null, "Desea editar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if(a==JOptionPane.OK_OPTION){
                        
                    jtModelo1.removeRow(tasiento.getSelectedRow());   
                    
                    }                    //EVENTOS MODIFICAR
                }
                if(boton.getName().equals("e")){
                      int a= JOptionPane.showConfirmDialog(null, "Desea eliminar este registro", "Confirmar", JOptionPane.OK_CANCEL_OPTION);
                    if(a==JOptionPane.OK_OPTION){
                    jtModelo1.removeRow(tasiento.getSelectedRow());   
                    
                    }
                    //EVENTOS ELIMINAR
                }
            }
            if(value instanceof JCheckBox){
                //((JCheckBox)value).doClick();
                JCheckBox ch = (JCheckBox)value;
                if(ch.isSelected()==true){
                    ch.setSelected(false);
                }
                if(ch.isSelected()==false){
                    ch.setSelected(true);
                }
                
            }
        }
    }//GEN-LAST:event_tasientoMouseClicked

    private void jthaberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jthaberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jthaberActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        tasiento.setDefaultRenderer(Object.class, new Render());

        vcodigo=this.pcodigo.getText();
        vnombre=this.pnombre.getText();
        vdebe=this.jtdebe.getText();
        vhaber=this.jthaber.getText();
//        int año = fechaA.getCalendar().get(Calendar.YEAR);
//        int mes = fechaA.getCalendar().get(Calendar.MONTH);
//        int dia = fechaA.getCalendar().get(Calendar.DAY_OF_MONTH);
//        vfecha =(año+"/"+mes+"/"+dia);
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyy-MM-dd");
        vfecha = DateFor.format(fechaA.getDate());
        System.out.println(""+vfecha);
        
        if(vcodigo.isEmpty()||vnombre.isEmpty()||vfecha.isEmpty()){
                        JOptionPane.showMessageDialog(null, "Llene todos los datos", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }else{
            JButton btn2 = new JButton("Eliminar");
            btn2.setName("e");

            jtModelo1.addRow(new Object[]{
                vcodigo,vnombre,vdebe,vhaber,vfecha,btn2
            });
            this.limpiarjtex();
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tcodigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tcodigosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tcodigosMouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
            Conector cc = new Conector();
            Connection cn = cc.conectar();
            String consult = "insert into asiento(debe,haber,codigo,nombrec,nasiento,fecha) values(?,?,?,?,?,?)";
            String qry = "SELECT nasiento FROM asiento ORDER BY  nasiento DESC LIMIT 1";
        try {
            Statement stmt = cn.createStatement();
             ResultSet rs  = stmt.executeQuery(qry);
             System.out.println("aqui");
             int numecoAsiento= rs.getInt("nasiento");             
             numecoAsiento=numecoAsiento+1;
        
            if (tasiento.getRowCount() == 0) {
               JOptionPane.showMessageDialog(null, "No Existen Datos", "Advertencia", JOptionPane.WARNING_MESSAGE);
            } else {                
                for (int i = 0; i < tasiento.getRowCount(); i++) {
                    vcodigo=(String) tasiento.getValueAt(i, 0);
                    vnombre=(String) tasiento.getValueAt(i, 1);
                    vdebe=(String) tasiento.getValueAt(i, 2);
                    vhaber=(String) tasiento.getValueAt(i, 3);
                    vfecha=(String) tasiento.getValueAt(i, 4);
                    //vnumeroAsiento = (String) tasiento.getValueAt(i, 5);

                  PreparedStatement ps = cn.prepareStatement(consult);

                  if(vhaber.isEmpty()){
                    System.out.println("entro en debe");
                    ps.setDouble(1, Double.parseDouble(vdebe));
                    ps.setDouble(2, 0.0);
                    ps.setInt(3, Integer.parseInt(vcodigo));
                    ps.setString(4, vnombre);
                    ps.setInt(5, numecoAsiento);
                    ps.setString(6,vfecha);



                  }
                  else if(vdebe.isEmpty()){
                        System.out.println("entro en haber");

                        ps.setDouble(1, 0.0);
                        ps.setDouble(2, Double.parseDouble(vhaber));
                        ps.setInt(3, Integer.parseInt(vcodigo));
                        ps.setString(4, vnombre);
                        ps.setInt(5, numecoAsiento);
                        ps.setString(6,vfecha);

                  }
                  else{
                      System.out.println("error no entro");
                  }
                  ps.executeUpdate();


                }
            JOptionPane.showMessageDialog(null,"Asiento Guardado con exito.","Con exito",JOptionPane.INFORMATION_MESSAGE);
  
             
           }

        } catch ( Exception e ) {

          System.err.println( e.getClass().getName() + ": " + e.getMessage() );
        }

        this.limpiarjtex();
        this.eliminar();
        cc.close();

        
        
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                     AsientosConatables  newasiento = null;
          try {
              newasiento = new AsientosConatables();
          } catch (SQLException ex) {
              Logger.getLogger(asientoContable.class.getName()).log(Level.SEVERE, null, ex);
          }
                newasiento.setSize(900, 540);
                 newasiento.setLocation(0,0);
                content.removeAll();
             content.add(newasiento, BorderLayout.CENTER);
             content.revalidate();
             content.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechaA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField jtcodigoC;
    private javax.swing.JTextField jtdebe;
    private javax.swing.JTextField jthaber;
    private javax.swing.JTextField nombreE;
    private javax.swing.JTextField pcodigo;
    private javax.swing.JTextField pnombre;
    private javax.swing.JTable tasiento;
    private javax.swing.JTable tcodigos;
    // End of variables declaration//GEN-END:variables
}
